{
    "openapi": "3.1.0",
    "info": {
        "title": "Nylas v3 Scheduler APIs",
        "version": "v3",
        "summary": "The Nylas APIs for Scheduler",
        "description": "<div style=\"padding:24px; background-color: #F5FFFD; border: 1px solid #00A88C; color: #161717\">This API reference documentation covers the <strong>Nylas Scheduler API</strong>. See the see the <strong><a href=\"/docs/api/v3/admin/\">Administration API documentation</a></strong> for information about working with Nylas applications, authentication, connectors, and webhook subscriptions.</div>\n\nThe **Nylas Scheduler API** is designed using the [REST](http://en.wikipedi[...]",
        "contact": {
            "url": "https://www.nylas.com/"
        }
    },
    "servers": [
        {
            "url": "https://api.us.nylas.com",
            "description": "US"
        },
        {
            "url": "https://api.eu.nylas.com",
            "description": "EU"
        }
    ],
    "tags": [
        {
            "name": "Configurations",
            "description": "A configuration is a collection of event settings and preferences. Nylas Scheduler stores Configuration objects in the Scheduler database and loads them as Scheduling Pages in the Scheduler UI.\n\nA configuration can be either private if it uses a session, or public if it does not. By default, Nylas creates public configurations (`requires_session_auth: false`). To create a private configuration, set `requires_session_auth` to `true`.\n\nAfter you create a private con[...]"
        },
        {
            "name": "Sessions",
            "description": "Nylas Scheduler uses session IDs to authorize requests to the [`/v3/scheduling/availability`](/docs/api/v3/scheduler/#get-/v3/scheduling/availability) and [`/v3/scheduling/bookings`](/docs/api/v3/scheduler/#post-/v3/scheduling/bookings) endpoints.\n\nWhen you create a session, you must include the ID of an existing [Configuration object](/docs/api/v3/scheduler/#tag--Configurations). Sessions are only required for private configurations (`requires_session_auth: true`).[...]"
        },
        {
            "name": "Availability",
            "description": "Nylas Scheduler uses the `/v3/scheduling/availability` endpoint to retrieve availability information. When you make a request, Nylas validates the provided session ID and uses it to retrieve the related Configuration object.\n\n## Availability scopes\n\nThe table below lists the Availability endpoints and which scopes they require. The table shortens the full scope URI for space reasons, so add the prefix for the provider when requesting scopes.\n\nThe ☑️ in each colu[...]"
        },
        {
            "name": "Bookings",
            "description": "Nylas Scheduler uses the `/v3/scheduling/bookings` endpoint to manage bookings.\n\n## Booking types\n\nNylas Scheduler supports two booking types, `booking` and `organizer-confirmation`.\n\n`booking` represents a regular booking flow. When the booking type is `organizer-confirmation`, Nylas creates an event marked \"Pending\" in the organizer's calendar. It then sends an confirmation request email to the organizer, which includes a link to a page where the organizer c[...]"
        }
    ],
    "paths": {
        "/v3/grants/{grant_id}/scheduling/configurations": {
            "post": {
                "summary": "Create a Configuration object",
                "tags": [
                    "Configurations"
                ],
                "x-scopes": {
                    "google": {
                        "min": "https://www.googleapis.com/auth/calendar.readonly",
                        "others": "https://www.googleapis.com/auth/calendar"
                    },
                    "microsoft": {
                        "min": "https://graph.microsoft.com/Calendars.Read",
                        "others": "https://graph.microsoft.com/Calendars.ReadWrite"
                    }
                },
                "operationId": "post-configurations",
                "description": "Creates a Configuration object that you use to define the settings and preferences for a scheduling session.",
                "security": [
                    {
                        "NYLAS_API_KEY": []
                    }
                ]
            },
            "get": {
                "summary": "Return all Configuration objects",
                "tags": [
                    "Configurations"
                ],
                "operationId": "get-configurations",
                "description": "Returns all Configuration objects.",
                "security": [
                    {
                        "NYLAS_API_KEY": []
                    }
                ]
            }
        },
        "/v3/grants/{grant_id}/scheduling/configurations/{configuration_id}": {
            "get": {
                "summary": "Return a Configuration object",
                "tags": [
                    "Configurations"
                ],
                "operationId": "get-configurations-id",
                "description": "Returns a specific Configuration object.",
                "security": [
                    {
                        "NYLAS_API_KEY": []
                    }
                ]
            },
            "put": {
                "summary": "Update a configuration",
                "tags": [
                    "Configurations"
                ],
                "x-scopes": {
                    "google": {
                        "min": "https://www.googleapis.com/auth/calendar.readonly",
                        "others": "https://www.googleapis.com/auth/calendar"
                    },
                    "microsoft": {
                        "min": "https://graph.microsoft.com/Calendars.Read",
                        "others": "https://graph.microsoft.com/Calendars.ReadWrite"
                    }
                },
                "operationId": "put-configurations-id",
                "description": "Update a specific configuration.\n\nWhen you make a `PUT` request, Nylas replaces all data in the nested object with the information\nincluded in your request. For more information, see\n[Updating objects](/docs/api/v3/scheduler/#overview--updating-objects).",
                "security": [
                    {
                        "NYLAS_API_KEY": []
                    }
                ]
            },
            "delete": {
                "summary": "Delete a Configuration object",
                "tags": [
                    "Configurations"
                ],
                "operationId": "delete-configurations-id",
                "description": "Deletes a specific Configuration object. You cannot delete a Configuration object that has active sessions.",
                "security": [
                    {
                        "NYLAS_API_KEY": []
                    }
                ]
            }
        },
        "/v3/scheduling/sessions": {
            "post": {
                "summary": "Create a session",
                "tags": [
                    "Sessions"
                ],
                "operationId": "post-sessions",
                "description": "Creates a new short-lived session that you can pass to the Scheduling Component to enforce end-user authentication. Your request must include the ID of an existing Configuration object.",
                "security": [
                    {
                        "NYLAS_API_KEY": []
                    }
                ]
            }
        },
        "/v3/scheduling/sessions/{session_id}": {
            "delete": {
                "summary": "Delete a session",
                "tags": [
                    "Sessions"
                ],
                "operationId": "delete-session",
                "description": "Deletes a specific session.",
                "security": [
                    {
                        "NYLAS_API_KEY": []
                    }
                ]
            }
        },
        "/v3/scheduling/availability": {
            "get": {
                "summary": "Get Availability",
                "tags": [
                    "Availability"
                ],
                "x-scopes": {
                    "google": {
                        "min": "https://www.googleapis.com/auth/calendar.readonly",
                        "others": "https://www.googleapis.com/auth/calendar"
                    },
                    "microsoft": {
                        "min": "https://graph.microsoft.com/Calendars.Read",
                        "others": "https://graph.microsoft.com/Calendars.ReadWrite"
                    }
                },
                "operationId": "get-availability",
                "description": "Gets available time slots within the specified time range, using the rules defined in the Configuration object.</br></br>   Nylas validates the provided session ID and uses it to retrieve the related Configuration object. If you created a [public configuration](/docs/api/v3/scheduler/#tag--Configurations), you don't need to include the `Authorization` request header with a session ID, but you must pass the Configuration object ID as a query parameter.",
                "security": [
                    {
                        "SCHEDULER_SESSION_TOKEN": []
                    }
                ]
            }
        },
        "/v3/scheduling/bookings": {
            "post": {
                "summary": "Book an event",
                "tags": [
                    "Bookings"
                ],
                "x-scopes": {
                    "google": {
                        "min": "https://www.googleapis.com/auth/calendar.events",
                        "others": "https://www.googleapis.com/auth/calendar"
                    },
                    "microsoft": {
                        "min": "https://graph.microsoft.com/Calendars.ReadWrite",
                        "others": ""
                    }
                },
                "operationId": "post-bookings",
                "description": "Books an event with the participants listed in the session's Configuration object, using the details from the Configuration object. The `start_time` and `end_time` must correspond to a valid time slot returned by the [Scheduling  Availability endpoint](/docs/api/v3/scheduler/#get-/v3/scheduling/availability) using the same configuration.</br></br>\n Nylas validates the session ID and uses it to retrieve the related Configuration object. If you created a [public co[...]",
                "security": [
                    {
                        "SCHEDULER_SESSION_TOKEN": []
                    }
                ]
            }
        },
        "/v3/scheduling/bookings/{booking_id}": {
            "get": {
                "summary": "Return a Booking object",
                "tags": [
                    "Bookings"
                ],
                "x-scopes": {
                    "google": {
                        "min": "https://www.googleapis.com/auth/calendar.events",
                        "others": "https://www.googleapis.com/auth/calendar"
                    },
                    "microsoft": {
                        "min": "https://graph.microsoft.com/Calendars.ReadWrite",
                        "others": ""
                    }
                },
                "operationId": "get-bookings-id",
                "description": "Returns a specific booking object.</br></br>   Nylas validates the provided session ID and uses it to retrieve the related Configuration object. If you created a [public configuration](/docs/api/v3/scheduler/#tag--Configurations), you don't need to include the `Authorization` request header with a session ID, but you must pass the Configuration object ID as a query parameter.",
                "security": [
                    {
                        "SCHEDULER_SESSION_TOKEN": []
                    }
                ]
            },
            "patch": {
                "summary": "Reschedule a booking",
                "tags": [
                    "Bookings"
                ],
                "x-scopes": {
                    "google": {
                        "min": "https://www.googleapis.com/auth/calendar.events",
                        "others": "https://www.googleapis.com/auth/calendar"
                    },
                    "microsoft": {
                        "min": "https://graph.microsoft.com/Calendars.ReadWrite",
                        "others": ""
                    }
                },
                "operationId": "patch-bookings-id",
                "description": "Reschedule a specific booking. Nylas also updates the associated event on the provider.\n\nNylas validates the provided session ID and uses it to retrieve the related Configuration. If you\ncreated a [public configuration](/docs/api/v3/scheduler/#tag--Configurations), you don't need to\ninclude the `Authorization` request header with a session ID, but you must pass the Configuration\nID as a query parameter.\n\nWhen you make a `PATCH` request, Nylas replaces all d[...]",
                "security": [
                    {
                        "SCHEDULER_SESSION_TOKEN": []
                    }
                ]
            },
            "put": {
                "summary": "Confirm a booking",
                "tags": [
                    "Bookings"
                ],
                "x-scopes": {
                    "google": {
                        "min": "https://www.googleapis.com/auth/calendar.events",
                        "others": "https://www.googleapis.com/auth/calendar"
                    },
                    "microsoft": {
                        "min": "https://graph.microsoft.com/Calendars.ReadWrite",
                        "others": ""
                    }
                },
                "operationId": "put-bookings-id",
                "description": "Confirm or cancel a specific pending booking. Nylas also updates the event linked to the booking\non the provider.\n\nNylas validates the provided session ID and uses it to retrieve the related Configuration. If you\ncreated a [public configuration](/docs/api/v3/scheduler/#tag--Configurations), you don't need to\ninclude the `Authorization` request header with a session ID, but you must pass the Configuration\nID as a query parameter.\n\nWhen you make a `PUT` requ[...]",
                "security": [
                    {
                        "SCHEDULER_SESSION_TOKEN": []
                    }
                ]
            },
            "delete": {
                "summary": "Delete a booking",
                "tags": [
                    "Bookings"
                ],
                "x-scopes": {
                    "google": {
                        "min": "https://www.googleapis.com/auth/calendar.events",
                        "others": "https://www.googleapis.com/auth/calendar"
                    },
                    "microsoft": {
                        "min": "https://graph.microsoft.com/Calendars.ReadWrite",
                        "others": ""
                    }
                },
                "operationId": "delete-bookings-id",
                "description": "Deletes an specific booking. Nylas also cancels the event linked to the booking on the provider.</br></br>   Nylas validates the provided session ID and uses it to retrieve the related Configuration object. If you created a [public configuration](/docs/api/v3/scheduler/#tag--Configurations), you don't need to include the `Authorization` request header with a session ID, but you must pass the Configuration object ID as a query parameter.",
                "security": [
                    {
                        "SCHEDULER_SESSION_TOKEN": []
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "ACCESS_TOKEN": {
                "scheme": "bearer",
                "type": "http",
                "bearerFormat": "Access token",
                "description": "The Nylas **access token** for a specific grant. Issued as part of OAuth 2.1 flow token exchange."
            },
            "NYLAS_API_KEY": {
                "scheme": "bearer",
                "type": "http",
                "bearerFormat": "API key",
                "description": "The Nylas **API key** provides application-level access to APIs and all grants. You can generate these from the v3 Dashboard. Learn more about [authorizing requests in Nylas v3](/docs/v3/auth/)."
            },
            "SCHEDULER_SESSION_TOKEN": {
                "scheme": "bearer",
                "type": "http",
                "bearerFormat": "Session ID",
                "description": "The Nylas Scheduler **session ID** that Scheduler UI Components use to authorize API requests."
            }
        }
    }
}
